### ISSUE TITLE
Register new version with compat bounds

### ISSUE THREAD

**Issue by sefffal** [emmt/OIFITS.jl#14]
Hello,
Would you mind releasing a new version of this package with updated compat bounds?
I can submit a PR if needed.

Thanks!

**Comment by emmt** [comment]
Hello,

Thanks for the suggestion.

I have just registered a new major version (1.0.0) with compat bounds. If you were using the former official version (0.4), see the [`NEWS.md`]() file for a list of changes. If you were using the `master` version, the data-block types have chanched to match the name of the corresponding  FITS extension (as in v0.4). Below is a Perl script to perform the changes in the code if you were using the `master` version:

```perl
#! /usr/bin/perl -pi.orig
s/\bOIArray\b/OI_ARRAY/g;
s/\bOICorr\b/OI_CORR/g;
s/\bOIFlux\b/OI_FLUX/g;
s/\bOIInsPol\b/OI_INSPOL/g;
s/\bOIT3\b/OI_T3/g;
s/\bOITarget\b/OI_TARGET/g;
s/\bOIVis2\b/OI_VIS2/g;
s/\bOIVis\b/OI_VIS/g;
s/\bOIWavelength\b/OI_WAVELENGTH/g;
```

Assuming that you save this script as `update.pl`, you can apply the changes by

```bash
perl -pi.orig update.pl FILE1FILE2 ...
```

to convert type names in files `FILE1`, `FILE2`, ... saving the original files with the `.orig` extension (in case of). If `update.pl`  is set as executable script (`chmod 755 update.pl`), you can directly do:

```sh
update.pl FILE1 FILE2 ...
```

**Comment by sefffal** [comment]
Thank you very much!
