### ISSUE TITLE
julia v0.4 issues

### ISSUE THREAD

**Issue by fabienbaron** [emmt/OIFITS.jl#5]
In julia v0.4 on my Arch Linux or Ubuntu boxes.  
- The statements "++nerrs" in oifile.jl on lines 197 AND 205 triggers an error on module import. Replacing by nerrs++ does not work, but nerrs +=1 does.
- Lots of warnings (but none fatal): startswith should replace beginswith, Union{} instead of Union(), parse(Int,s) instead of int(s::AbstractString).

**Comment by Lightjohn** [comment]
Should be good now.
If you still have the warnings do Pkg.remove("OIFITS") then Pkg.add("OIFITS")
