### ISSUE TITLE
OIFITS.jl and OIFITS 2

### ISSUE THREAD

**Issue by DeVerMyst** [emmt/OIFITS.jl#6]
Because of some optional table and fields (name, size) OIFITS fails to read some OIFITS2 files.
Here is the error:

reading OI-FITS OI_TARGET in HDU 2
reading OI-FITS OI_ARRAY in HDU 3
reading OI-FITS OI_WAVELENGTH in HDU 4
WARNING: unknown OI-FITS data-block "OI_FLUX"
skipping HDU 5 (no OI-FITS data)
WARNING: missing keyword "CORRNAME" in OI-FITS OI_VIS data-block
WARNING: missing keyword "AMPORDER" in OI-FITS OI_VIS data-block
WARNING: missing column "CORRINDX_VISAMP" in OI-FITS OI_VIS data-block
WARNING: missing column "CORRINDX_VISPHI" in OI-FITS OI_VIS data-block
WARNING: missing column "RVIS" in OI-FITS OI_VIS data-block
WARNING: missing column "RVISERR" in OI-FITS OI_VIS data-block
WARNING: missing column "CORRINDX_RVIS" in OI-FITS OI_VIS data-block
WARNING: missing column "IVIS" in OI-FITS OI_VIS data-block
WARNING: missing column "IVISERR" in OI-FITS OI_VIS data-block
WARNING: missing column "CORRINDX_IVIS" in OI-FITS OI_VIS data-block
ERROR: expecting a 2-D array value for field "visrefmap" in OI_VIS
 in error at error.jl:21
 in build_datablock at /Users/antonyschutz/.julia/v0.3/OIFITS/src/oidata.jl:444
 in read_datablock at /Users/antonyschutz/.julia/v0.3/OIFITS/src/oifile.jl:214
 in read_datablock at /Users/antonyschutz/.julia/v0.3/OIFITS/src/oifile.jl:182
 in load at /Users/antonyschutz/.julia/v0.3/OIFITS/src/oifile.jl:226
 in readoifits at /Users/antonyschutz/.julia/v0.4/PAINTER.jl/src/painteroifits.jl:51
 in painter at /Users/antonyschutz/.julia/v0.4/PAINTER.jl/src/paintertools.jl:406
 in include at /Applications/Julia-0.3.9.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.9.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/antonyschutz/Desktop/Beauty Contest/TestObj2V2.jl, in expression starting on line 75

**Comment by emmt** [comment]
supporting OIFITS2 is a work in progress, you may check the current master version
